/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.travis;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Provides a list of acceptable values for the result of an action
 * 
 */
public enum Status implements org.apache.thrift.TEnum {
  /**
   * this action resulted in failure
   */
  FAILURE(0),
  /**
   * this action resulted in success
   */
  SUCCESS(1);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 0:
        return FAILURE;
      case 1:
        return SUCCESS;
      default:
        return null;
    }
  }
}
