/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.woot4moo;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * The commands that a Job knows about
 * 
 */
public enum Command implements org.apache.thrift.TEnum {
  /**
   * Start the job
   */
  START(0),
  /**
   * Stop the job
   */
  STOP(1);

  private final int value;

  private Command(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Command findByValue(int value) { 
    switch (value) {
      case 0:
        return START;
      case 1:
        return STOP;
      default:
        return null;
    }
  }
}
